version: "3.9"

services:
  web:
    build: .
    image: bookclub-django
    container_name: bookclub-web
    command: daphne -b 0.0.0.0 -p 8000 BookCLUB.asgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=BookCLUB.settings
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    depends_on:
      - db
      - redis
    networks:
      - bookclub-net


  db:
    image: postgres:15
    container_name: bookclub-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookclub
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookclub-net

  redis:
    image: redis:7
    container_name: bookclub-redis
    restart: always
    expose:
      - "6379"
    networks:
      - bookclub-net

  nginx:
    image: nginx:alpine
    container_name: bookclub-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app
    depends_on:
      - web
      - redis
    restart: always
    networks:
      - bookclub-net

volumes:
  pgdata:

networks:
  bookclub-net:
    driver: bridge
